[package]
name = "version"
version = "0.1.0-dev"
description = "🦀 The blazing fast way to check what version of grep you're using, written in Rust."
edition = "2018"

[dependencies]
clap = { version = "3.0.10", features = ["cargo"] }
regex = "^1.5.4"

[build-dependencies]
serde_json = "^1.0.59"
uneval = "^0.2.1"
