[package]
name = "version"
version = "0.1.0-dev"
description = "🦀 The blazing fast way to check what version of grep you're using, written in Rust."
edition = "2018"

[dependencies]
clap = "~2.33.3"

[build-dependencies]
serde_json = "1.0.59"
uneval = "0.2.1"
